- hosts: ubuntu
  tasks:
  # apt update
  # apt install
    - name: Install apache httpd
      apt:
          name: apache2
          state: present
          update_cache: yes

  # apt install unzip
    - name: Install apache unzip
      apt:
          name: unzip
          state: present
          update_cache: yes

  # download
  # unzip file fiu.zip
    - name: Unarchive a file that needs to be downloaded 
      unarchive:
          src: https://www.free-css.com/assets/files/free-css-templates/download/page288/fiu.zip
          dest: /tmp/
          remote_src: yes

  # mv /tmp/html/* /var/www/html/ 
    - name: Move template files to /var/www/html/
      shell: rm -rf /var/www/html/* && mv /tmp/html/* /var/www/html/